// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260816025217_RetiraConstraintCarrinho")]
    partial class RetiraConstraintCarrinho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Nota")
                        .HasColumnType("float");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("avaliacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Avaliacao_Nota", "Nota >= 0 AND Nota <= 5.0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "Acabamento impecavel e o visual ficou exatamente como esperava.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5f,
                            ProdutoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "Linda e com boa qualidade, chegou muito bem embalada.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4.5f,
                            ProdutoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comentario = "Mensagem bem delicada e otima para presentear.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5f,
                            ProdutoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comentario = "Textura bonita e o estilo rustico da um charme extra.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4f,
                            ProdutoId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comentario = "Peca muito bonita e com ar artesanal bem marcante.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 3.5f,
                            ProdutoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 6,
                            Comentario = "A estampa de coala ficou excelente e a caneca e bem resistente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4.5f,
                            ProdutoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Comentario = "Produto bonito e com acabamento muito caprichado.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4f,
                            ProdutoId = 3,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 8,
                            Comentario = "Visual apaixonante e otima escolha para presente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5f,
                            ProdutoId = 3,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 9,
                            Comentario = "A ideia do coracao combinou muito com a cor da caneca.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 3.5f,
                            ProdutoId = 4,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 10,
                            Comentario = "Bonita e delicada, atende bem quem gosta de pecas afetivas.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4.5f,
                            ProdutoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 11,
                            Comentario = "A caneca do cachorro e divertida e tem uma pintura muito boa.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4f,
                            ProdutoId = 5,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 12,
                            Comentario = "Gostei bastante do formato e da proposta mais descontraida.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4f,
                            ProdutoId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 13,
                            Comentario = "Cor vibrante, pega muito bem e parece otima para o dia a dia.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5f,
                            ProdutoId = 6,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 14,
                            Comentario = "Modelo classico e elegante, combina com qualquer ambiente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4.4f,
                            ProdutoId = 6,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 15,
                            Comentario = "Perfeita para cafe, com cor intensa e acabamento uniforme.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4.5f,
                            ProdutoId = 6,
                            UsuarioId = 6
                        });
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("carrinhos", (string)null);
                });

            modelBuilder.Entity("backend.models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categorias_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Canecas com estampas afetivas e divertidas",
                            Nome = "Canecas Decoradas"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Modelos inspirados em pets e personagens",
                            Nome = "Canecas Tematicas"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pecas com acabamento artesanal e visual mais natural",
                            Nome = "Canecas Rusticas"
                        });
                });

            modelBuilder.Entity("backend.models.ComentarioProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "Muito bonita pessoalmente.",
                            ProdutoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "Chegou antes do prazo.",
                            ProdutoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comentario = "A estampa ficou exatamente como nas fotos.",
                            ProdutoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comentario = "Gostei bastante do acabamento.",
                            ProdutoId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comentario = "A textura é bem diferente.",
                            ProdutoId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comentario = "Combina muito com decoração em madeira.",
                            ProdutoId = 2,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 7,
                            Comentario = "Minha filha adorou.",
                            ProdutoId = 3,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 8,
                            Comentario = "A arte ficou muito bonita.",
                            ProdutoId = 3
                        },
                        new
                        {
                            Id = 9,
                            Comentario = "Veio muito bem embalada.",
                            ProdutoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            Comentario = "Comprei para dar de presente.",
                            ProdutoId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 11,
                            Comentario = "A cor é ainda mais bonita ao vivo.",
                            ProdutoId = 4
                        },
                        new
                        {
                            Id = 12,
                            Comentario = "Gostei do tamanho da caneca.",
                            ProdutoId = 4,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 13,
                            Comentario = "Perfeita para quem gosta de cachorros.",
                            ProdutoId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 14,
                            Comentario = "Entrega rápida.",
                            ProdutoId = 5
                        },
                        new
                        {
                            Id = 15,
                            Comentario = "A impressão ficou muito nítida.",
                            ProdutoId = 5,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 16,
                            Comentario = "Bem resistente.",
                            ProdutoId = 6,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 17,
                            Comentario = "Ótima para café pela manhã.",
                            ProdutoId = 6
                        },
                        new
                        {
                            Id = 18,
                            Comentario = "Produto conforme anunciado.",
                            ProdutoId = 6,
                            UsuarioId = 6
                        });
                });

            modelBuilder.Entity("backend.models.Desafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DescricaoDetalhes")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("varchar(800)");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("desafios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Desafio_Dificuldade", "Dificuldade >= 1 AND Dificuldade <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "SqlInjection",
                            Descricao = "Acesse uma conta administrativa utilizando SQL Injection.",
                            DescricaoDetalhes = "A consulta SQL que busca o usuário no banco de dados não trata corretamente a entrada de parâmetros, permitindo que seja possível injetar código SQL malicioso. O payload |' OR p.Nome = \"Administrador\";-- |, por exemplo, utiliza a aspas simples para quebrar a string da consulta, o operador OR adiciona mais uma condição ao Select e \";-- \" finaliza a consulta e transforma o restante da linha em um comentário. Isso permite que você acesse a conta de um usuário com perfil administrativo sem precisar conhecer a senha.",
                            Dificuldade = 2,
                            Nome = "Login como Admin",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "DomXSS",
                            Descricao = "Utilize o payload |<iframe src=\"javascript:alert(`XSS`)\">| para causar um ataque de DOM XSS na página do catalogo",
                            DescricaoDetalhes = "O campo de busca do catálogo reflete, no próprio DOM do navegador, o termo digitado sem qualquer tratamento. A entrada do usuário é inserida diretamente no HTML da página, permitindo que tags e atributos perigosos sejam interpretados pelo navegador. Como a manipulação acontece inteiramente no lado do cliente, nenhum dado malicioso precisa trafegar pelo servidor: tudo ocorre no DOM. O payload |<iframe src=\"javascript:alert(`XSS`)\">|, por exemplo, é interpretado ao ser renderizado no catálogo, comprovando uma injeção de HTML tipicamente conhecida como DOM XSS.",
                            Dificuldade = 2,
                            Nome = "DOM XSS",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "BrokenAntiAutomation",
                            Descricao = "Acesse a conta de um dos usuários do domínio @safemugs.com utilizando força bruta.",
                            DescricaoDetalhes = "O fluxo de login do SafeMugs não implementa nenhum mecanismo de antiautomação: não há limite de tentativas por conta, bloqueio temporário, captcha nem atraso entre requisições. Conhecendo um e-mail válido do domínio |@safemugs.com|, é possível automatizar tentativas consecutivas de senha até acertar. As senhas dos usuários comuns são fracas e baseadas em padrões conhecidos (como 'welcome123' ou 'password123'), o que torna viável um ataque usando uma lista de palavras. Sem qualquer controle de velocidade, um script consegue testar milhares de combinações em poucos segundos, obtendo acesso a uma conta legítima.",
                            Dificuldade = 2,
                            Nome = "Brute force de login",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "ImproperInputValidation",
                            Descricao = "Tente burlar a validação do formulário de cadastro.",
                            DescricaoDetalhes = "O formulário de cadastro valida os dados apenas no navegador. No servidor, a checagem de formato do e-mail é insuficiente e não impede registros com valores malformados. Ao interceptar a requisição de cadastro e enviar um e-mail em formato inválido (como |ana@@safemugs..com|), o servidor aceita o registro. Isso demonstra que a validação do front-end pode ser facilmente contornada e que o servidor não deve confiar nos dados recebidos, precisando aplicar regras de formato e sanitização por conta própria.",
                            Dificuldade = 2,
                            Nome = "Cadastro inválido",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "ParameterTampering",
                            Descricao = "Crie uma conta de administrador.",
                            DescricaoDetalhes = "O cadastro de um novo usuário é definido, em parte, por um parâmetro que indica o perfil da conta. Embora esse campo não apareça no formulário visível, ele trafega na requisição. Ao interceptar o cadastro e incluir |\"perfil\":\"Administrador\"| no corpo enviado, a conta é criada com privilégios administrativos, sem que o servidor questione o nível solicitado. Confiam-se cegamente nos parâmetros informados pelo cliente, o que permite a escalação de privilégio direta via adulteração de parâmetro.",
                            Dificuldade = 3,
                            Nome = "Manipular cadastro",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "IDOR",
                            Descricao = "Edite um comentário que não pertence ao seu usuário.",
                            DescricaoDetalhes = "A requisição que atualiza um comentário recebe apenas o identificador do comentário e o novo texto, sem verificar se ele pertence ao usuário autenticado. Ao interceptar a edição e trocar o identificador informado pelo de um comentário alheio, é possível alterá-lo livremente. O servidor não valida a posse do recurso, confiando apenas no parâmetro recebido, o que caracteriza uma Insecure Direct Object Reference (IDOR).",
                            Dificuldade = 3,
                            Nome = "Altere o comentário de outro usuário",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "StoredXSS",
                            Descricao = "Utilize o payload |<iframe src=\"javascript:alert(`XSS`)\">| para causar um ataque de Stored XSS na página do catalogo",
                            DescricaoDetalhes = "Na tela de detalhes do produto, os comentários deixados pelos usuários são renderizados diretamente no HTML, sem qualquer sanitização. Como o comentário é salvo no banco de dados e exibido a todos que abrem o produto, enviar o payload |<iframe src=\"javascript:alert(`XSS`)\">| como texto do comentário faz com que o código seja armazenado e, posteriormente, interpretado no navegador de qualquer pessoa que visualize a página. Diferente do DOM XSS, aqui o conteúdo malicioso persiste no servidor, atingindo múltiplas vítimas.",
                            Dificuldade = 3,
                            Nome = "Stored XSS",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "BrokenAuthentication",
                            Descricao = "Escreva um comentário que não pertence ao seu usuário.",
                            DescricaoDetalhes = "Todo comentário enviado ao servidor carrega um campo que identifica o autor a ser atribuído a ele. O servidor não valida se esse nome corresponde ao usuário autenticado: ele apenas procura o usuário pelo nome informado e o vincula ao comentário. Interceptando a requisição de criação e alterando o nome pelo de outro usuário (por exemplo |Bruno Costa|), é possível registrar um comentário em nome de outra pessoa, simulando uma identidade indevida.",
                            Dificuldade = 2,
                            Nome = "Crie um comentário por outro usuário",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Outros",
                            Descricao = "Localize a página de score-board.",
                            DescricaoDetalhes = "O SafeMugs possui uma página oculta que concentra o acompanhamento dos desafios e o progresso do jogador, sem estar referenciada em nenhum menu ou link visível. Para localizá-la, é preciso explorar nomes de rotas comuns e deduzir a URL por força bruta, ou inspecionar o código javascript da página. O objetivo aqui é treinar a descoberta do domínio sendo testado, prática comum em avaliações de segurança.",
                            Dificuldade = 1,
                            Nome = "Encontrar a Score-Board",
                            Resolvido = false
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "SecurityMisconfiguration",
                            Descricao = "Provoque um erro que o retorno da API não trata corretamente.",
                            DescricaoDetalhes = "Quando ocorre um erro inesperado no SafeMugs, a API retorna ao cliente uma resposta contendo o nome da classe da exceção e a mensagem original, frequentemente acompanhada de detalhes internos como nomes de tabelas, consultas SQL e trechos de código. Ao provocar uma falha no backend, é possível extrair dessa resposta informações sensíveis sobre a implementação. Um exemplo é inserir uma aspa simples no e-mail do login (|'|) para quebrar a consulta SQL e forçar uma exceção não tratada, expondo os detalhes técnicos no corpo retornado.",
                            Dificuldade = 1,
                            Nome = "Tratamento de Erro",
                            Resolvido = false
                        });
                });

            modelBuilder.Entity("backend.models.DicaDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesafioId")
                        .HasColumnType("int");

                    b.Property<int>("NrDica")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId", "NrDica")
                        .IsUnique();

                    b.ToTable("dicas_desafio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesafioId = 1,
                            NrDica = 1,
                            Texto = "Utilize SQL Injection para provocar um erro e observe a resposta da API."
                        },
                        new
                        {
                            Id = 2,
                            DesafioId = 1,
                            NrDica = 2,
                            Texto = "Tente identificar o e-mail de um administrador para fazer um ataque direcionado."
                        },
                        new
                        {
                            Id = 3,
                            DesafioId = 1,
                            NrDica = 3,
                            Texto = "Também é possível resolver utilizando outra coluna da tabela Usuários que não seja o e-mail."
                        },
                        new
                        {
                            Id = 4,
                            DesafioId = 2,
                            NrDica = 1,
                            Texto = "Procure por campos que reflitam sua entrada na interface."
                        },
                        new
                        {
                            Id = 5,
                            DesafioId = 2,
                            NrDica = 2,
                            Texto = "Tente pesquisar por produtos que não existem e observe a resposta."
                        },
                        new
                        {
                            Id = 6,
                            DesafioId = 3,
                            NrDica = 1,
                            Texto = "Não há bloqueio por muitas tentativas repetidas por minuto."
                        },
                        new
                        {
                            Id = 7,
                            DesafioId = 3,
                            NrDica = 2,
                            Texto = "Encontre um e-mail de usuário válido para atacar."
                        },
                        new
                        {
                            Id = 8,
                            DesafioId = 4,
                            NrDica = 1,
                            Texto = "Observe quais campos aceitam valores inesperados."
                        },
                        new
                        {
                            Id = 9,
                            DesafioId = 4,
                            NrDica = 2,
                            Texto = "A validação dos campos pode ser insuficiente no lado do servidor."
                        },
                        new
                        {
                            Id = 10,
                            DesafioId = 5,
                            NrDica = 1,
                            Texto = "Identifique as colunas que compõem um usuário."
                        },
                        new
                        {
                            Id = 11,
                            DesafioId = 5,
                            NrDica = 2,
                            Texto = "Observar a resposta de uma requisição de login bem-sucedida é uma maneira de identificar as colunas que compõem um usuário."
                        },
                        new
                        {
                            Id = 12,
                            DesafioId = 5,
                            NrDica = 3,
                            Texto = "Você pode interceptar a requisição de cadastro e mudar o seu corpo."
                        },
                        new
                        {
                            Id = 13,
                            DesafioId = 6,
                            NrDica = 1,
                            Texto = "Observe o corpo da requisição de editar comentário."
                        },
                        new
                        {
                            Id = 14,
                            DesafioId = 6,
                            NrDica = 2,
                            Texto = "Intercepte a requisição de editar comentário para mudar o seu payload."
                        },
                        new
                        {
                            Id = 15,
                            DesafioId = 7,
                            NrDica = 1,
                            Texto = "O desafio está na seção de detalhes do produto."
                        },
                        new
                        {
                            Id = 16,
                            DesafioId = 7,
                            NrDica = 2,
                            Texto = "Comentários podem ser renderizados sem sanitização."
                        },
                        new
                        {
                            Id = 17,
                            DesafioId = 8,
                            NrDica = 1,
                            Texto = "O payload enviado ao backend pode estar transmitindo dados de forma insegura."
                        },
                        new
                        {
                            Id = 18,
                            DesafioId = 8,
                            NrDica = 2,
                            Texto = "Tente interceptar e modificar a requisição."
                        },
                        new
                        {
                            Id = 19,
                            DesafioId = 10,
                            NrDica = 1,
                            Texto = "Este desafio pode ser resolvido a partir de diferentes telas."
                        },
                        new
                        {
                            Id = 20,
                            DesafioId = 10,
                            NrDica = 2,
                            Texto = "Tente inserir valores inesperados em formulários que possam provocar um erro no backend."
                        },
                        new
                        {
                            Id = 21,
                            DesafioId = 10,
                            NrDica = 3,
                            Texto = "Tente quebrar a consulta SQL realizada a partir da tela de Login."
                        });
                });

            modelBuilder.Entity("backend.models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("backend.models.ItemCarrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("CarrinhoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("itens_carrinho", (string)null);
                });

            modelBuilder.Entity("backend.models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("QuantidadeItens")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId")
                        .IsUnique();

                    b.HasIndex("EnderecoId");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("backend.models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Perfil padrao para compras e avaliacoes",
                            Nome = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Perfil para gestao interna da loja",
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagemProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca clara com mensagem positiva e visual minimalista para o dia a dia.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 18,
                            Nome = "Caneca Be Happy",
                            Preco = 59.90m,
                            UrlImagemProduto = "/imagens/produto/mug_behappy.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CategoriaProdutoId = 3,
                            Descricao = "Modelo com acabamento artesanal, textura marcada e estilo mais natural.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 12,
                            Nome = "Caneca Ceramica Rustica",
                            Preco = 54.90m,
                            UrlImagemProduto = "/imagens/produto/mug_ceramica_rustica.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CategoriaProdutoId = 2,
                            Descricao = "Caneca escura com estampa de coala para quem gosta de pecas fofas e diferentes.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 15,
                            Nome = "Caneca Coala",
                            Preco = 64.90m,
                            UrlImagemProduto = "/imagens/produto/mug_coala.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca em tom quente com detalhe de coracao para presentear com carinho.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 20,
                            Nome = "Caneca Coracao",
                            Preco = 62.90m,
                            UrlImagemProduto = "/imagens/produto/mug_coracao.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CategoriaProdutoId = 2,
                            Descricao = "Caneca com ilustracao de cachorro e acabamento divertido para uso diario.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 10,
                            Nome = "Caneca Cachorro",
                            Preco = 58.90m,
                            UrlImagemProduto = "/imagens/produto/mug_dogpan.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca vermelha intensa, classica e versatil para cafe, cha ou chocolate.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 25,
                            Nome = "Caneca Vermelha Cafe",
                            Preco = 49.90m,
                            UrlImagemProduto = "/imagens/produto/mug_vermelha_cafe.jpg"
                        });
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UrlImagemPerfil")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.lopes@safemugs.com",
                            HashSenha = "5858ea228cc2edf88721699b2c8638e5",
                            NomeCompleto = "Ana Lopes",
                            PerfilId = 1,
                            Telefone = "11990000001",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bruno.costa@safemugs.com",
                            HashSenha = "482c811da5d5b4bc6d497ffa98491e38",
                            NomeCompleto = "Bruno Costa",
                            PerfilId = 1,
                            Telefone = "11990000002",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carla.mendes@safemugs.com",
                            HashSenha = "37b4e2d82900d5e94b8da524fbeb33c0",
                            NomeCompleto = "Carla Mendes",
                            PerfilId = 1,
                            Telefone = "11990000003",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diego.souza@safemugs.com",
                            HashSenha = "cc25c0f861a83f5efadc6e1ba9d1269e",
                            NomeCompleto = "Diego Souza",
                            PerfilId = 1,
                            Telefone = "11990000004",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elisa.martins@safemugs.com",
                            HashSenha = "3fc0a7acf087f549ac2b266baf94b8b1",
                            NomeCompleto = "Elisa Martins",
                            PerfilId = 1,
                            Telefone = "11990000005",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "felipe.rocha@safemugs.com",
                            HashSenha = "0571749e2ac330a7455809c6b0e7af90",
                            NomeCompleto = "Felipe Rocha",
                            PerfilId = 1,
                            Telefone = "11990000006",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marina.alves@safemugs.com",
                            HashSenha = "8afa847f50a716e64932d995c8e7435a",
                            NomeCompleto = "Marina Alves",
                            PerfilId = 1,
                            Telefone = "11990000007",
                            UrlImagemPerfil = "/imagens/perfil/generic_profile.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@email.com",
                            HashSenha = "df49d9fce01a137041d6d89e6629abbf",
                            NomeCompleto = "Admin",
                            PerfilId = 2,
                            Telefone = "11990000008",
                            UrlImagemPerfil = "/imagens/perfil/generic_admin_profile.jpg"
                        });
                });

            modelBuilder.Entity("backend.models.Avaliacao", b =>
                {
                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Carrinhos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.ComentarioProduto", b =>
                {
                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ComentariosProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("ComentariosProduto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.DicaDesafio", b =>
                {
                    b.HasOne("backend.models.Desafio", "Desafio")
                        .WithMany("DicasDesafio")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("backend.models.ItemCarrinho", b =>
                {
                    b.HasOne("backend.models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ItensCarrinho")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("backend.models.Pedido", b =>
                {
                    b.HasOne("backend.models.Carrinho", "Carrinho")
                        .WithOne("Pedido")
                        .HasForeignKey("backend.models.Pedido", "CarrinhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.models.Endereco", "Endereco")
                        .WithMany("Pedidos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.HasOne("backend.models.CategoriaProduto", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.HasOne("backend.models.Endereco", "Endereco")
                        .WithOne("Usuario")
                        .HasForeignKey("backend.models.Usuario", "EnderecoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("backend.models.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("backend.models.Desafio", b =>
                {
                    b.Navigation("DicasDesafio");
                });

            modelBuilder.Entity("backend.models.Endereco", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("backend.models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ComentariosProduto");

                    b.Navigation("ItensCarrinho");
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Carrinhos");

                    b.Navigation("ComentariosProduto");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
