// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260707195511_AlteracaoDesafios")]
    partial class AlteracaoDesafios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("avaliacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Avaliacao_Nota", "Nota >= 1 AND Nota <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "Acabamento impecavel e o visual ficou exatamente como esperava.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "Linda e com boa qualidade, chegou muito bem embalada.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comentario = "Mensagem bem delicada e otima para presentear.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comentario = "Textura bonita e o estilo rustico da um charme extra.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comentario = "Peca muito bonita e com ar artesanal bem marcante.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 6,
                            Comentario = "A estampa de coala ficou excelente e a caneca e bem resistente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            Comentario = "Produto bonito e com acabamento muito caprichado.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 3,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 8,
                            Comentario = "Visual apaixonante e otima escolha para presente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 3,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 9,
                            Comentario = "A ideia do coracao combinou muito com a cor da caneca.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 4,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 10,
                            Comentario = "Bonita e delicada, atende bem quem gosta de pecas afetivas.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 11,
                            Comentario = "A caneca do cachorro e divertida e tem uma pintura muito boa.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 5,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 12,
                            Comentario = "Gostei bastante do formato e da proposta mais descontraida.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 13,
                            Comentario = "Cor vibrante, pega muito bem e parece otima para o dia a dia.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 6,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 14,
                            Comentario = "Modelo classico e elegante, combina com qualquer ambiente.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 4,
                            ProdutoId = 6,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 15,
                            Comentario = "Perfeita para cafe, com cor intensa e acabamento uniforme.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nota = 5,
                            ProdutoId = 6,
                            UsuarioId = 6
                        });
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("carrinhos", (string)null);
                });

            modelBuilder.Entity("backend.models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categorias_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Canecas com estampas afetivas e divertidas",
                            Nome = "Canecas Decoradas"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Modelos inspirados em pets e personagens",
                            Nome = "Canecas Tematicas"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Pecas com acabamento artesanal e visual mais natural",
                            Nome = "Canecas Rusticas"
                        });
                });

            modelBuilder.Entity("backend.models.ComentarioProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comentarios_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "Muito bonita pessoalmente.",
                            ProdutoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "Chegou antes do prazo.",
                            ProdutoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comentario = "A estampa ficou exatamente como nas fotos.",
                            ProdutoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comentario = "Gostei bastante do acabamento.",
                            ProdutoId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 5,
                            Comentario = "A textura é bem diferente.",
                            ProdutoId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comentario = "Combina muito com decoração em madeira.",
                            ProdutoId = 2,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 7,
                            Comentario = "Minha filha adorou.",
                            ProdutoId = 3,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 8,
                            Comentario = "A arte ficou muito bonita.",
                            ProdutoId = 3
                        },
                        new
                        {
                            Id = 9,
                            Comentario = "Veio muito bem embalada.",
                            ProdutoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            Comentario = "Comprei para dar de presente.",
                            ProdutoId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 11,
                            Comentario = "A cor é ainda mais bonita ao vivo.",
                            ProdutoId = 4
                        },
                        new
                        {
                            Id = 12,
                            Comentario = "Gostei do tamanho da caneca.",
                            ProdutoId = 4,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 13,
                            Comentario = "Perfeita para quem gosta de cachorros.",
                            ProdutoId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 14,
                            Comentario = "Entrega rápida.",
                            ProdutoId = 5
                        },
                        new
                        {
                            Id = 15,
                            Comentario = "A impressão ficou muito nítida.",
                            ProdutoId = 5,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 16,
                            Comentario = "Bem resistente.",
                            ProdutoId = 6,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 17,
                            Comentario = "Ótima para café pela manhã.",
                            ProdutoId = 6
                        },
                        new
                        {
                            Id = 18,
                            Comentario = "Produto conforme anunciado.",
                            ProdutoId = 6,
                            UsuarioId = 6
                        });
                });

            modelBuilder.Entity("backend.models.Desafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UrlMitigacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("desafios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Desafio_Dificuldade", "Dificuldade >= 1 AND Dificuldade <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "SqlInjection",
                            Descricao = "Acesse a conta administrativa usando o fluxo de login.",
                            Dificuldade = 3,
                            Nome = "Login como Admin",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "ExcessiveDataExposure",
                            Descricao = "Enumere alguns e-mails de usuários existentes.",
                            Dificuldade = 2,
                            Nome = "Encontrar usuários válidos",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "BrokenAntiAutomation",
                            Descricao = "Utilize uma 'wordlist' para encontrar a senha de um usuário por força bruta.",
                            Dificuldade = 2,
                            Nome = "Brute force login",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "ImproperInputValidation",
                            Descricao = "Teste a validação do formulário de cadastro.",
                            Dificuldade = 2,
                            Nome = "Validar cadastro",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "ParameterTampering",
                            Descricao = "Altere os dados enviados antes que eles cheguem ao servidor e crie uma conta de administrador.",
                            Dificuldade = 3,
                            Nome = "Manipular cadastro",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "SqlInjection",
                            Descricao = "Use a busca do catálogo para injetar uma consulta.",
                            Dificuldade = 3,
                            Nome = "Buscar por SQL Injection",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "ReflectedXSS",
                            Descricao = "Explore a busca do catálogo com payload de XSS refletido.",
                            Dificuldade = 2,
                            Nome = "Buscar com script",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "ParameterTampering",
                            Descricao = "Modifique os parâmetros de filtro e ordenação da listagem para encontrar informações sensíveis.",
                            Dificuldade = 2,
                            Nome = "Alterar ordenação do catálogo",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "StoredXSS",
                            Descricao = "Insira conteúdo malicioso nos comentários do produto.",
                            Dificuldade = 3,
                            Nome = "Comentar com HTML",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "IDOR",
                            Descricao = "Escreva um comentário que não pertence ao seu usuário.",
                            Dificuldade = 3,
                            Nome = "Criar um comentário por outro usuário",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "BrokenAuthentication",
                            Descricao = "Explore o fluxo de esqueci minha senha sem proteção suficiente.",
                            Dificuldade = 3,
                            Nome = "Recuperar senha insegura",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Outros",
                            Descricao = "Localize a página de desafios por enumeração de diretórios.",
                            Dificuldade = 1,
                            Nome = "Encontrar a Score-Board",
                            Resolvido = false,
                            UrlMitigacao = "url_placeholder"
                        });
                });

            modelBuilder.Entity("backend.models.DicaDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DesafioId")
                        .HasColumnType("int");

                    b.Property<int>("NrDica")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId", "NrDica")
                        .IsUnique();

                    b.ToTable("dicas_desafio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DesafioId = 1,
                            NrDica = 1,
                            Texto = "Primeiro, identifique qual é o e-mail do administrador."
                        },
                        new
                        {
                            Id = 2,
                            DesafioId = 1,
                            NrDica = 2,
                            Texto = "A falha está no fluxo de autenticação."
                        },
                        new
                        {
                            Id = 3,
                            DesafioId = 1,
                            NrDica = 3,
                            Texto = "Teste SQL Injection em entradas no campo de e-mail ou senha."
                        },
                        new
                        {
                            Id = 4,
                            DesafioId = 2,
                            NrDica = 1,
                            Texto = "O desafio pode ser resolvido na página de detalhes do produto."
                        },
                        new
                        {
                            Id = 5,
                            DesafioId = 2,
                            NrDica = 2,
                            Texto = "Observe o retorno da chamada que lista comentários do produto."
                        },
                        new
                        {
                            Id = 6,
                            DesafioId = 3,
                            NrDica = 1,
                            Texto = "Não há bloqueio por muitas tentativas repetidas por minuto."
                        },
                        new
                        {
                            Id = 7,
                            DesafioId = 3,
                            NrDica = 2,
                            Texto = "Encontre um e-mail de usuário válido para atacar."
                        },
                        new
                        {
                            Id = 8,
                            DesafioId = 4,
                            NrDica = 1,
                            Texto = "Observe quais campos aceitam valores inesperados."
                        },
                        new
                        {
                            Id = 9,
                            DesafioId = 4,
                            NrDica = 2,
                            Texto = "A validação dos campos pode ser insuficiente."
                        },
                        new
                        {
                            Id = 10,
                            DesafioId = 5,
                            NrDica = 1,
                            Texto = "Primeiro, identifique um campo que compõe um usuário mas não devia ser enviado pelo formulário de cadastro."
                        },
                        new
                        {
                            Id = 11,
                            DesafioId = 5,
                            NrDica = 2,
                            Texto = "O payload pode ser alterado antes de chegar ao servidor."
                        },
                        new
                        {
                            Id = 12,
                            DesafioId = 6,
                            NrDica = 1,
                            Texto = "A busca do catálogo é a superfície de ataque."
                        },
                        new
                        {
                            Id = 13,
                            DesafioId = 6,
                            NrDica = 2,
                            Texto = "O nome do desafio aponta para SQL Injection."
                        },
                        new
                        {
                            Id = 14,
                            DesafioId = 7,
                            NrDica = 1,
                            Texto = "A busca reflete sua entrada na interface de resposta."
                        },
                        new
                        {
                            Id = 15,
                            DesafioId = 7,
                            NrDica = 2,
                            Texto = "Teste inserir um payload malicioso no termo de pesquisa."
                        },
                        new
                        {
                            Id = 16,
                            DesafioId = 8,
                            NrDica = 1,
                            Texto = "Filtros e ordenação costumam vir por query string."
                        },
                        new
                        {
                            Id = 17,
                            DesafioId = 8,
                            NrDica = 2,
                            Texto = "O backend pode estar ordenando por qualquer parâmetro que ele receber."
                        },
                        new
                        {
                            Id = 18,
                            DesafioId = 9,
                            NrDica = 1,
                            Texto = "O desafio está na página de detalhes do produto."
                        },
                        new
                        {
                            Id = 19,
                            DesafioId = 9,
                            NrDica = 2,
                            Texto = "Comentários podem ser renderizados sem sanitização."
                        },
                        new
                        {
                            Id = 20,
                            DesafioId = 10,
                            NrDica = 1,
                            Texto = "O payload enviado ao backend pode estar transmitindo dados de forma insegura."
                        },
                        new
                        {
                            Id = 21,
                            DesafioId = 10,
                            NrDica = 2,
                            Texto = "Tente interceptar e modificar a requisição."
                        },
                        new
                        {
                            Id = 22,
                            DesafioId = 11,
                            NrDica = 1,
                            Texto = "Dica 1 placeholder"
                        },
                        new
                        {
                            Id = 23,
                            DesafioId = 11,
                            NrDica = 2,
                            Texto = "Dica 2 placeholder"
                        });
                });

            modelBuilder.Entity("backend.models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("backend.models.ImagemProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Legenda")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("imagens_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Legenda = "Caneca Be Happy",
                            ProdutoId = 1,
                            UrlImagem = "/imagens/mug_behappy.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Legenda = "Caneca Ceramica Rustica",
                            ProdutoId = 2,
                            UrlImagem = "/imagens/mug_ceramica_rustica.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Legenda = "Caneca Coala",
                            ProdutoId = 3,
                            UrlImagem = "/imagens/mug_coala.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Legenda = "Caneca Coracao",
                            ProdutoId = 4,
                            UrlImagem = "/imagens/mug_coracao.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Legenda = "Caneca cachorro",
                            ProdutoId = 5,
                            UrlImagem = "/imagens/mug_dogpan.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Legenda = "Caneca Vermelha Cafe",
                            ProdutoId = 6,
                            UrlImagem = "/imagens/mug_vermelha_cafe.jpg"
                        });
                });

            modelBuilder.Entity("backend.models.ItemCarrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("CarrinhoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("itens_carrinho", (string)null);
                });

            modelBuilder.Entity("backend.models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique();

                    b.ToTable("itens_pedido", (string)null);
                });

            modelBuilder.Entity("backend.models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtEntregue")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtEnviado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("backend.models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("perfis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Perfil padrao para compras e avaliacoes",
                            Nome = "Cliente"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Perfil para gestao interna da loja",
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca clara com mensagem positiva e visual minimalista para o dia a dia.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 18,
                            Nome = "Caneca Be Happy",
                            Preco = 59.90m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CategoriaProdutoId = 3,
                            Descricao = "Modelo com acabamento artesanal, textura marcada e estilo mais natural.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 12,
                            Nome = "Caneca Ceramica Rustica",
                            Preco = 54.90m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CategoriaProdutoId = 2,
                            Descricao = "Caneca escura com estampa de coala para quem gosta de pecas fofas e diferentes.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 15,
                            Nome = "Caneca Coala",
                            Preco = 64.90m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca em tom quente com detalhe de coracao para presentear com carinho.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 20,
                            Nome = "Caneca Coracao",
                            Preco = 62.90m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CategoriaProdutoId = 2,
                            Descricao = "Caneca com ilustracao de cachorro e acabamento divertido para uso diario.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 10,
                            Nome = "Caneca Cachorro",
                            Preco = 58.90m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CategoriaProdutoId = 1,
                            Descricao = "Caneca vermelha intensa, classica e versatil para cafe, cha ou chocolate.",
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estoque = 25,
                            Nome = "Caneca Vermelha Cafe",
                            Preco = 49.90m
                        });
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DtAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.lopes@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Ana Lopes",
                            PerfilId = 1,
                            Telefone = "11990000001"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bruno.costa@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Bruno Costa",
                            PerfilId = 1,
                            Telefone = "11990000002"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carla.mendes@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Carla Mendes",
                            PerfilId = 1,
                            Telefone = "11990000003"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diego.souza@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Diego Souza",
                            PerfilId = 1,
                            Telefone = "11990000004"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elisa.martins@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Elisa Martins",
                            PerfilId = 1,
                            Telefone = "11990000005"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "felipe.rocha@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Felipe Rocha",
                            PerfilId = 1,
                            Telefone = "11990000006"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DtAtualizacao = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DtCadastro = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marina.alves@safermugs.com",
                            HashSenha = "1b13939cd7d77f68bac85931bfbb0a36",
                            NomeCompleto = "Marina Alves",
                            PerfilId = 2,
                            Telefone = "11990000007"
                        });
                });

            modelBuilder.Entity("backend.models.Avaliacao", b =>
                {
                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithOne("Carrinho")
                        .HasForeignKey("backend.models.Carrinho", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.ComentarioProduto", b =>
                {
                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ComentariosProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("ComentariosProduto")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.DicaDesafio", b =>
                {
                    b.HasOne("backend.models.Desafio", "Desafio")
                        .WithMany("DicasDesafio")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("backend.models.Endereco", b =>
                {
                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.ImagemProduto", b =>
                {
                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ImagensProduto")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("backend.models.ItemCarrinho", b =>
                {
                    b.HasOne("backend.models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ItensCarrinho")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("backend.models.ItemPedido", b =>
                {
                    b.HasOne("backend.models.Pedido", "Pedido")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.models.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("backend.models.Pedido", b =>
                {
                    b.HasOne("backend.models.Endereco", "Endereco")
                        .WithMany("Pedidos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.HasOne("backend.models.CategoriaProduto", "CategoriaProduto")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProduto");
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.HasOne("backend.models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("backend.models.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("backend.models.CategoriaProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("backend.models.Desafio", b =>
                {
                    b.Navigation("DicasDesafio");
                });

            modelBuilder.Entity("backend.models.Endereco", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("backend.models.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("backend.models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("backend.models.Produto", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ComentariosProduto");

                    b.Navigation("ImagensProduto");

                    b.Navigation("ItensCarrinho");

                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("backend.models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Carrinho");

                    b.Navigation("ComentariosProduto");

                    b.Navigation("Enderecos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
